theme: jekyll-theme-architect

title: <img src="https://github.com/RoseTec/JigSPuzzle/blob/master/src/main/resources/images/icon.png?raw=true" height="100" width="100" /> JigSPuzzle
show_downloads: true
debug_gh_pages: false
