package jigspuzzle.view.desktop.settings;

import java.awt.Dimension;

/**
 * A panel designed to be added in a JTabbedPane in the settings view
 *
 * @author RoseTec
 */
class SettingViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingViewPanel
     */
    public SettingViewPanel() {
        initComponents();

        TopToButtomLayoutManager layout = new TopToButtomLayoutManager();
        layout.OFFSET_BETWEEN_COMPONENTS = 7;
        layout.OFFSET_TOP = 5;
        layout.OFFSET_BUTTOM = 10;
        layout.OFFSET_LEFT = 7;
        layout.OFFSET_RIGHT = 5;
        setLayout(layout);
    }

    @Override
    public Dimension getMinimumSize() {
        return getLayout().minimumLayoutSize(this);
    }

    @Override
    public Dimension getPreferredSize() {
        return getLayout().preferredLayoutSize(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
