package jigspuzzle.view.desktop.about;

import java.util.Observable;
import jigspuzzle.controller.SettingsController;
import jigspuzzle.view.ImageGetter;
import jigspuzzle.view.desktop.swing.TopToButtomLayoutManager;
import jigspuzzle.view.desktop.swing.ImageJPanel;
import jigspuzzle.view.desktop.swing.JLabel;

/**
 * A dialog for details on JigSPuzzle.
 *
 * @author RoseTec
 */
public class AboutDialog extends javax.swing.JDialog {

    public AboutDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();

        // set layouts
        TopToButtomLayoutManager layoutMain = new TopToButtomLayoutManager();
        TopToButtomLayoutManager layoutPanels = new TopToButtomLayoutManager();

        layoutMain.OFFSET_BETWEEN_COMPONENTS = 25;
        layoutMain.OFFSET_LEFT = 20;
        layoutMain.OFFSET_RIGHT = 20;
        layoutMain.OFFSET_TOP = 20;

        layoutPanels.OFFSET_BETWEEN_COMPONENTS = 0;

        jPanel6.setLayout(layoutMain);
        jPanel2.setLayout(layoutPanels);
        jPanel3.setLayout(layoutPanels);

        // load language texts
        SettingsController.getInstance().addLanguageSettingsObserver((Observable o, Object arg) -> {
            loadLanguageTexts();
        });
        loadLanguageTexts();
    }

    /**
     * Shows the window where the user can see details on JigSPuzzle.
     */
    public void showAboutWindow() {
        this.setVisible(true);
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * Loads all texts from the settings in the current language.
     */
    private void loadLanguageTexts() {
        jLabel1.setText(SettingsController.getInstance().getLanguageText(12, 1));
        jLabel2.setText(SettingsController.getInstance().getLanguageText(12, 2));

        jLabel3.setText(SettingsController.getInstance().getLanguageText(12, 10));

        jLabel4.setText(SettingsController.getInstance().getLanguageText(12, 20));
        jLabel5.setText(SettingsController.getInstance().getLanguageText(12, 21));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new ImageJPanel(ImageGetter.getInstance().getJigSPuzzleImage());
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setName("about-window"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 440));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel4.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(jPanel4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("JigSPuzzle");

        jLabel2.setText("by RoseTec");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        jPanel6.add(jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);

        jPanel6.add(jPanel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5);

        jPanel6.add(jPanel3);

        jScrollPane1.setViewportView(jPanel6);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.dispose();
    }//GEN-LAST:event_formFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
